Coords
jimmyfnugent/tic-tac-go pull request #35
Opened 2016-10-10 22:34 UTC by apmcleod

Animations are working now I think! That includes wraparounds, halfway collisions, and full collisions. There is a slight pause halfway while it figures out all of the collisions, but it doesn't look too bad (actually, I kind of prefer it like that).

This also fixes #25, as I also changed the Pieces to use [0,1,2] for position, and changed things to use "row" "column" "horizontal" and "vertical" instead of x and y.

This fixes #33, as I call Piece.updateImageResourceFullPiece() before animating.

This fixes #30 as well. This is how each the animation logic works:
1. Create and add any dummy Pieces. These Pieces are initially off the edge of the board, and are used to ensure that wrap-arounds animate properly.
2. Animate all Pieces (including dummies) halfway.
3. Calculate and resolve halfway collisions (We could move the calculation out of this step to a step 0, but it doesn't seem too bad to me). This also performs any resolution on each Piece's dummies (player changes or removals).
4. Animate all Pieces (including dummies) the rest of the way.
5. Calculate and resolve full collisions (including for dummies a la step 3).
6. Remove all views from the board and repopulate. This both removes any dummy Pieces, as well as ensures that the normal Pieces are now moved to their proper locations (in case they were animated off the edge of the Board.

As a note, this also effects #26, since I removed redo/undo to make things simpler. If we add it back, we should look at doing it in a more efficient way, saving only what we need to.

2016-10-26 04:01 UTC, jimmyfnugent requested changes
Overall, looks really good! Thanks for doing this :-) got a few small comments,

2016-10-26 04:01 UTC, jimmyfnugent commented on src/com/tictacgo/data/Board.java
> +     * Update and get the dummy Pieces for each active Piece.
Some more explanation here would be good -- what are dummy pieces and why do we need them?

2016-10-26 04:01 UTC, jimmyfnugent commented on src/com/tictacgo/data/Piece.java
> +    private final Drawable X_FULL_DRAWABLE = ContextCompat.getDrawable(getContext(),
Nit: these would be better as static

2016-10-26 04:01 UTC, jimmyfnugent commented on src/com/tictacgo/data/Piece.java
> +    public void updateDummyPieces() {
IMO this class should be a fairly dumb "model" object that doesn't have any complicated logic in it. I'd move these new methods somewhere else like Board.

2016-10-26 10:38 UTC, apmcleod commented on src/com/tictacgo/data/Piece.java
> +    private final Drawable X_FULL_DRAWABLE = ContextCompat.getDrawable(getContext(),
For some reason, this requires a Context, which cannot be gotten statically. I agree that I'd rather not have 4*numPieces of these Drawables though... It seems there should be some possible optimization though, given that all of the Pieces are the same size.

2016-10-26 10:43 UTC, apmcleod commented on src/com/tictacgo/data/Board.java
>          }
So maybe here, replace the inside of the loop with: dummies.addAll(getDummyPieces(piece), and move the logic from Piece to the new method?

2016-10-26 10:44 UTC, apmcleod commented on src/com/tictacgo/data/Board.java
>          }
And here, change the inside of this loop to:

piece.updateImageResourceFullPiece();
pieceAnimators.add(getHalfwayAnimator(piece);

and move the logic from Piece to the new method here?

2016-10-26 10:45 UTC, apmcleod commented on src/com/tictacgo/data/Piece.java
> +    public void updateDummyPieces() {
That makes sense, so something similar to my two other comments?

2016-10-31 06:00 UTC, jimmyfnugent commented on src/com/tictacgo/data/Piece.java
> +    public void updateDummyPieces() {
Yup! Exactly what I was thinking.

2016-10-31 06:01 UTC, jimmyfnugent commented on src/com/tictacgo/data/Piece.java
> +    private final Drawable X_FULL_DRAWABLE = ContextCompat.getDrawable(getContext(),
Oh, I see. This is fine then.

2016-11-01 22:05 UTC, apmcleod commented on src/com/tictacgo/data/Board.java
> +            dummy.setVisibility(View.GONE);
This is the reason that the dummies (as the logic is now) MUST be tied to each one's Piece specifically. They are animated together in Piece.getHalfwayAnimator(), and they are hidden together here. I'm sure we could refactor things around, but we need to be able to get from a Piece to its dummies, and the most natural way to do that is to compute and store the dummies within each Piece itself.

2016-11-01 22:15 UTC, apmcleod commented on src/com/tictacgo/data/Piece.java
> +    public void updateDummyPieces() {
See my comments elsewhere. I tried this, but it turns out that Board needs to be able to get from a Piece to its dummies for dummy removal halfway through animation.

2016-11-01 22:18 UTC, apmcleod commented
I expanded the dummy comment as requested. Also, I don't think it's feasible at this time to move the dummy logic into Board. Specifically, the way the animation is done, there needs to be a good way to get from a Piece to its dummies directly. If animations (including halfway explosions) are precomputed at some point, we can look back at this.

Other than that, I think I've addressed all of your comments.

2016-11-03 05:15 UTC, jimmyfnugent commented
Okay, sounds good. Let's revisit the refactoring later. Thanks for doing this!

2016-11-03 05:15 UTC, jimmyfnugent approved these changes

2016-11-03 10:21 UTC, merged